### PR TITLE
Refactor and mavenize the project

### PR DESCRIPTION
**Pull request by TheLightMC**
A LOT of updates, converted to a maven project for easy compilation. Refactored a lot in order to improve a lot of the code.

### CODE REVIEW

**Comment by konsolas** [comment]
Compilcation error?

**Comment by TheLightMC** [comment]
@konsolas one that I created on accident

**Comment by konsolas** [comment]
"compilcation"

**Comment by TheLightMC** [comment]
Oops, meant compilation

**Comment by NotGGhost** [comment]
Can not merge and will not merge; API has been recoded.

**Comment by SpongyBacon** [comment]
racist af

**Comment by NotGGhost** [comment]
Joe, you treat your dog like a jew.

**Comment by TheLightMC** [comment]
You added the majority of the updates so just going to close this.

**Pull request closed without merging**
