### PR TITLE
Remove Unused Stuff + Add Some Supress Warnings Cause Eclipse

### PR DESCRIPTION
**Pull request by Fabricio20**
Yes, I use eclipse, I've tried IntelliJ but I didn't like the interface ( too much complicated for me ).

### CODE REVIEW

**Comment by NotGGhost** [comment]
Seems like most of the PR would just break jSkype, although I haven't tested it.

**Comment by NotGGhost** [comment]
I'll see about merging it later.

**Comment by NotGGhost** [comment]
Will not merge; you've broken several items.

**Comment by SpongyBacon** [comment]
I have a fix: Force yourself to use IntelliJ for a week. After, you'll love it.

**Comment by Fabricio20** [comment]
>I have a fix: Force yourself to use IntelliJ for a week. After, you'll love it.
Going to try that.

**Pull request closed without merging**
